### ISSUE TITLE
Gjøre det enklere og mer effektivt å bruke produksjonssystemet

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#167]
- [ ] nlbdev/produksjonsverktoy#34
- [ ] Bedre feilmeldinger nlbdev/produksjonssystem#73
- [x] ~Enklere e-post nlbdev/produksjonssystem#191 nlbdev/produksjonssystem#192~
- [x] Redusere mengden e-post der det er mulig nlbdev/produksjonssystem#160
- [x] Autotrigge bøker i "insert-metadata"-stegene dersom de ligger i noen sin liste i Quickbase nlbdev/produksjonssystem#168
- [x] Bedre oversikt over hvilke bøker som inneholder katalogiseringsfeil
  - Kanskje en tabell over alle bøker, sortert på katalogiseringsdato, med kolonner for boknummer for hvert format, valideringsstatus for katalogpostene, og katalogiseringsfeilmeldinger?
  - Må kanskje genereres av bibliofil-interface, sånn at man har tilgang på selve databasen
- [x] Vurdere å lage et ordentlig web-grensesnitt (med f.eks. "flask" i backend og "react" i frontend) med mulighet til å blant annet trigge bøker. Web-grensesnitt bør isåfall være et separat prosjekt og produksjonssystemet bør kun tilby et API. https://github.com/nlbdev/toolbox/issues/8
  - [ ] Kan diagrammet over systemet gjøres klikkbart? Sånn at man kan trykke på boksene og gå til en spesifikk pipeline eller mappe?
- [x] Se om vi kan redusere mengden triggete bøker, både for å bedre ytelse på server, og for å redusere mengden e-post. Trenger vi å autotrigge bøker på hverdager?
- [ ] ~I e-postene som går til bibliotekarer: vektlegge viktigheten av at katalogposten rettes opp. For eksempel: "Boken blir ikke produsert grunnet feil i katalogposten. Katalogposten brukes blant annet for å lage tittelside og kolofon.".~
- [x] "Trigge" ut-mappa, sånn at ikke pipelines som overvåker ut-mappa fra forrige steg bruker så lang tid på å oppdage at det har skjedd noe
- [x] ~Bedre ytelse nlbdev/produksjonssystem#100~
- [x] Signaturer kommer dobbelt nlbdev/produksjonssystem#171
- [x] ~~For hver produsent-liste: lag rapport over status for bøker nlbdev/produksjonssystem#182~~
- [ ] ~Automatisk trigging når metadata endres~ nlbdev/produksjonssystem#183
- [x] Inkluder tidspunkt for datagrunnlag brukt i valideringer nlbdev/produksjonssystem#184
- [x] "produksjonslinjer", og regneark for alle bøker i hver av dem nlbdev/produksjonssystem#185
- [ ] bruk zippede epub i mottaks-mappa: https://github.com/nlbdev/produksjonssystem/issues/238

**Comment by espso** [comment]
En del av disse burde kanskje være som egne saker. Skal vi gjøre det mer oversiktlig for hver enkelte bok med en webserver burde det kanskje være en database i bakgrunn med informasjon for bøker og produksjoner? Hvis ikke database så vil det jo funke å se hvilke mapper boka finnes i for å se hva som er produsert.

En ting som kanskje haster litt er autotrigging for insert metadata lista. Hvordan kan vi hente lista over bøker som venter på å bli produsert fra Quickbase?

Hvis du setter meg på noen saker så kan jeg starte litt når jeg får tid.

**Comment by josteinaj** [comment]
> En del av disse burde kanskje være som egne saker.

Enig. Tenkte bare å samle de her også som en litt overordnet oppgave.

Jeg håper vi slipper å bruke en database, men det kan godt hende vi får behov for det ja.

Jeg laget en sak på insert-metadata nå: #168

**Comment by espso** [comment]
Ok da lukker jeg den andre (Som var annerledes)

**Comment by josteinaj** [comment]
Aha, ja jeg glemte den. Bra.

**Comment by josteinaj** [comment]
Tilbakemelding fra Statped:

> ### Om filer automatisk generert på nytt i produksjonssystemet hos NLB av ukjent årsak
>
> En titt på utgave-ut/epub-til-innlesing mappen viser at 16 av våre 22 epub-til-innlesing filer har blitt generert på nytt i løpet av det siste døgnet. I løpet av de seneste dagene har vi kun satt i gang 2 av disse selv. Alle filene i mappen er generert på nytt etter 1 januar 2020, de fleste av uklar årsak.
Hvorfor er disse filene kjørt på nytt av systemet?
Dette innebærer sannsynligvis at feilen omtalt over nå berører alle filene klargjort for innlesing. 
Selv om denne feilen nå er oppdaget og forhåpentligvis rettes, så må alle filene genereres på nytt nok en gang og vi må deretter sjekke at alle utformat faktisk blir generert og at feilen er borte. 
Det blir nesten umulig for oss å bruke systemet slik det er lagt opp til under disse forholdene. 
Vi mister fullstendig oversikt og kontroll over hva som ligger i mappene våre.
Vi risikerer at endringer i konverteringen forårsaker feil i filene som vi ikke har mulighet til å oppdage når utformatene vi tidligere har sjekket blir overskrevet uten at vi selv har satt i gang prosessen. 
For øyeblikket har vi 22 filer i systemet, men hvis hele årets bokproduksjon skal bruke nytt produksjonssystem blir det mange flere.
>
> Det dukker til stadighet opp lignende utfordringer som krever kontinuerlig overvåkning fra vår side, krever mye ressurser og forsinker alle prosessene, men som er lite synlige for ledelsen som forventer effektiv bruk av nytt produksjonssystem for produksjon av årets bokbestillinger. 
Vi må få på plass rutiner som forhindrer dette. Informasjon om endringer i etterkant er bedre enn ingenting, men vi bør utarbeide noen felles regler for hvordan endringer iverksettes i systemet.

Dette må vi gjøre tydeligere når vi får satt opp et brukergrensesnitt. Kanskje til og med slå av automatiske konverteringer der boka i ut-mappa finnes fra før? I alle fall forsøke å vise om boka i ut-mappa er basert på siste versjon av bok i inn-mappa, eller ikke, sånn at man vet om ut-fila er nyeste versjon. Se: #216
